### ISSUE TITLE
Push access

### ISSUE THREAD

**Issue by chenglou** [reasonml-community/bs-cookie-parser#1]
@mransan is it possible to give me [npm publishing access](https://www.npmjs.com/package/bs-cookie-parser) for this package? I'm upgrading the bs-platform dependency and would like to bump this package's version. 

cc @ncthbrt

**Comment by ncthbrt** [comment]
I don't have publish rights either unfortunately. And it looks like @mransan isn't very active on github at the moment. Didn't respond the last time I pinged him.

**Comment by chenglou** [comment]
Got access just now. I've added you too =)

**Comment by ncthbrt** [comment]
Thanks Cheng Lou :)
